DROP SCHEMA IF EXISTS `container_db`;
CREATE SCHEMA IF NOT EXISTS `container_db`;
USE `container_db`;


CREATE TABLE IF NOT EXISTS `USER` (
	`PORT` INT AUTO_INCREMENT NOT NULL,
	`FULL_NAME` NVARCHAR(100) NOT NULL,		
   `EMAIL` VARCHAR(40) NULL,
   `CONTAINER_NAME` VARCHAR(40) NULL,
   
   PRIMARY KEY(`PORT`)
) ENGINE=InnoDB AUTO_INCREMENT=1024 DEFAULT CHARSET=utf8mb4 COLLATE=UTF8MB4_UNICODE_CI;

